clear;clc; close all
lonx=[-60:1:20];
latx=[-60:1:20];
xlon=[1:length(lonx)];
ylat=[1:length(latx)];
ystart=1993;yend=2020;
timex=[datenum(ystart,1,1):datenum(yend,12,31)];
ttotal=length(timex);

index_x1=find(lonx>=-60 & lonx <=-30);
index_x2=find(latx>=-55 & latx <=-30);
lonx=lonx(index_x1);
latx=latx(index_x2);
timex=[datenum(ystart,1,1):datenum(yend,12,31)];

%%
datasets={'HFlux-driven MHWs';'ADV-driven MHWs ';'HFlux-driven MCSs';'ADV-driven MCSs'};

load('../step3v2_hobday_localmin_nolag.mat')
[xx,yy,nn,mm]=size(data_mean);

datau1=nan(xx,yy,nn);
datav1=nan(xx,yy,nn);
for n=1:nn
for x=1:5:xx
    for y=1:5:yy
datau1(x,y,n)=data_m(x,y,n,7);
datav1(x,y,n)=data_m(x,y,n,8);
    end
end
end

datau2=nan(xx,yy);datav2=nan(xx,yy);
datau2(2,21)=.1;datav2(2,21)=0;
[vx,vy]=meshgrid(lonx,latx);

[vx2,vy2]=meshgrid(lonx,latx);
%%
%data_c(:,6)=[-85 85];

figure1=figure;
hold on
for m=1:6
   for n=1:nn
       if n==1 | n==4
hm(1)=subtightplot(6,4,(m-1)*4+n,[.02 .02],[.04 .04],[.04 .04]);
       else
hm(1)=subtightplot(6,4,(m-1)*4+n,[.02 .02],[.04 .04],[.02 .02]);           
       end
m_proj('miller','lon',[min(lonx) -30],'lat',[-55 -30]);

hold on
m_pcolor(lonx,latx,squeeze(data_mean(:,:,n,m))');
colormap(othercolor('BuDRd_12',16));
caxis([xmin(n,m) xmax(n,m)]) 
[c,h]=m_contour(lonx,latx,squeeze(data_m(:,:,n,m))',data_c(:,m),'linestyle','-','linecolor','k');
clabel(c,h,data_c(:,m),'Color', 'k', 'Rotation', 0,'labelspacing', 1200,'fontsize',14);
if n==nn;co = colorbar; ylabel(co,units_name(m)); clear co ;end

if m==5;[vx,vy]=meshgrid(lonx,latx);
[h1]=m_quiver(vx,vy,squeeze(datau1(:,:,n))'*50,squeeze(datav1(:,:,n))'*50,0,'MaxHeadSize',2,'color','r'); 
set(h1,'color','k','MaxHeadSize',2,'Linewidth',1.2)
axis equal
end
%------BMC
a1=[-54 -49 -49 -54 -54];
b1=[-43 -43 -38 -38 -43];
h=m_line(a1,b1,'color','k','linewidth',2,'linestyle','-');

hold on
m_coast('patch',[.7 .7 .7],'edgecolor','none');
if m==6
m_grid('tickdir','out','linewi',2,...
    'xtick',[-60:15:20],'ytick',[-60:10:20],...
    'fontsize',12);
else
 m_grid('tickdir','out','linewi',2,...
    'xtick',[-60:15:20],'ytick',[-60:10:20],'xticklabel',[],...
    'fontsize',12);   
end
if m==5 & n==2
[h1]=m_quiver(vx2,vy2,squeeze(datau2)'*50,squeeze(datav2)'*50,0,'MaxHeadSize',2,'color','k'); 
m_text(lonx(2),latx(24),'0.1 N m^{-2}','color','k','fontsize',12)
end
set(gca,'box','on','fontsize',16);grid('on') 
if m==1;title([cell2mat(datasets(n))],'fontsize',14) ;end
if n==1;ylabel([cell2mat(dname(m))],'fontsize',14);end   
   end
end
%-------
annotation(figure1,'textbox',...
    [0.020 0.98 0.030 0.022],...
    'String',{'a)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.24 0.98 0.030 0.022],...
    'String','b)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.49 0.98 0.030 0.022],...
    'String','c)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.71 0.98 0.030 0.022],...
    'String','d)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%---------------------------------
annotation(figure1,'textbox',...
    [0.007 0.8 0.030 0.022],...
    'String',{'e)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.24 0.8 0.030 0.022],...
    'String','f)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.8 0.030 0.022],...
    'String','g)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.685 0.82 0.030 0.022],...
    'String','h)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%--------------------------
annotation(figure1,'textbox',...
    [0.007 0.646 0.030 0.022],...
    'String',{'i)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.24 0.646 0.030 0.022],...
    'String','j)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.646 0.030 0.022],...
    'String','k)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.685 0.646 0.030 0.022],...
    'String','l)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%----------------------------
annotation(figure1,'textbox',...
    [0.002 0.487 0.030 0.022],...
    'String',{'m)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.22 0.487 0.030 0.022],...
    'String','n)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.487 0.030 0.022],...
    'String','o)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.682 0.5 0.030 0.022],...
    'String','p)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%---------------------------
annotation(figure1,'textbox',...
    [0.007 0.3313 0.030 0.022],...
    'String',{'q)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.24 0.3313 0.030 0.022],...
    'String','r)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.3313 0.030 0.022],...
    'String','s)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.69 0.35 0.030 0.022],...
    'String','t)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%---------------------------
annotation(figure1,'textbox',...
    [0.007 0.16 0.030 0.022],...
    'String',{'u)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.24 0.16 0.030 0.022],...
    'String','v)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.16 0.030 0.022],...
    'String','w)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.682 0.18 0.030 0.022],...
    'String','x)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%%
set(gcf,'units','points','color','w')
set(gcf,'Units','inches',...
 'Position',[0 0 9 9],'rend','painters',...
 'PaperPositionMode','auto')

figt=['step2 hobday.jpeg'];;
%print('-djpeg',figt,'-r300');
fig = gcf;
fig.PaperPositionMode = 'auto';
%set(gca,'Color',[0.5 0.5 0.5])
set(gcf, 'InvertHardCopy', 'off');
print('-djpeg',figt,'-r600');

