clear;clc; close all
ystart=1993;yend=2020;
load(['../../../../../../../../datasets\GLORYS12V1d/step9_v1_BCO_STUV/data.' num2str(ystart) '.'  num2str(1)  '.mat'],'latx','lonx')
xlon=[1:length(lonx)];
ylat=[1:length(latx)];
latx=double(latx);
lonx=double(lonx);
timex=[datenum(ystart,1,1):datenum(yend,12,31)];
ttotal=length(timex);


timex=[datenum(ystart,1,1):datenum(yend,12,31)];

%%
datasets={'HFlux-driven MHWs';'ADV-driven MHWs ';'HFlux-driven MCSs';'ADV-driven MCSs'};
load('../step3v2_hobday_therm_9v1.mat')
data=data_mean(:,:,:,3);
load('../step3v2_hobday_localmin_nolag.mat')
[xx,yy,nn,mm]=size(data_mean);
data_mean(:,:,:,5)=data;
[vx2,vy2]=meshgrid(lonx,latx);


%---------(4) EKE
xmin(1:4,4) =-100; xmax(1:4,4)=100;
units_name(4)={'J m^{-3}'};
data_c(:,4)=[-1000 10000];
dname(4)={'EKE'};
%-----------(3)  MLD

xmin(1:4,3) =-10; xmax(1:4,3)=10;
units_name(3)={'m'};
dname(3)={'MLD'};
data_c(:,3)=[-10 10];

%-----------(5)  thermocline depth

xmin(1:4,5) =-150; xmax(1:4,5)=150;
units_name(5)={'m'};
dname(5)={'Pycnocline'};
data_c(:,5)=[-150 150];
%%

figure1=figure;
hold on
for m=1:5
   for n=1:nn
hm(1)=subtightplot(5,4,(m-1)*4+n,[.02 .02],[.04 .04],[.04 .04]);
m_proj('miller','lon',[min(lonx) max(lonx)],'lat',[min(latx) max(latx)]);

hold on
m_pcolor(lonx,latx,squeeze(data_mean(:,:,n,m))');
colormap(othercolor('BuDRd_12',16));
caxis([xmin(n,m) xmax(n,m)]) 
%[c,h]=m_contour(lonx,latx,squeeze(data_m(:,:,n,m))',data_c(:,m),'linestyle','-','linecolor','k');
%clabel(c,h,data_c(:,m),'Color', 'k', 'Rotation', 0,'labelspacing', 1200,'fontsize',14);
if n==nn;co = colorbar; ylabel(co,units_name(m)); clear co ;end

if m==5;[vx,vy]=meshgrid(lonx,latx);
%[h1]=m_quiver(vx,vy,squeeze(datau1(:,:,n))'*5,squeeze(datav1(:,:,n))'*5.5,0,'MaxHeadSize',2,'color','r'); 
%set(h1,'color','k','MaxHeadSize',2,'Linewidth',1.2)
%axis equal
end
%------BMC
a1=[-54 -49 -49 -54 -54];
b1=[-43 -43 -38 -38 -43];
h=m_line(a1,b1,'color','k','linewidth',2,'linestyle','-');

hold on
m_coast('patch',[.7 .7 .7],'edgecolor','none');
if m==5
m_grid('tickdir','out','linewi',2,...
    'xtick',[-60:15:-45],'ytick',[-48:5:-28],...
    'fontsize',12);
else
 m_grid('tickdir','out','linewi',2,...
    'xtick',[-60:15:-45],'ytick',[-48:5:-28],'xticklabel',[],...
    'fontsize',12);   
end

set(gca,'box','on','fontsize',16);grid('on') 
if m==1;title([cell2mat(datasets(n))],'fontsize',14) ;end
if n==1;ylabel([cell2mat(dname(m))],'fontsize',14);end   
   end
end
%-------
annotation(figure1,'textbox',...
    [0.012 0.96 0.030 0.022],...
    'String',{'a)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.238 0.96 0.030 0.022],...
    'String','b)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.96 0.030 0.022],...
    'String','c)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.68 0.96 0.030 0.022],...
    'String','d)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%---------------------------------
annotation(figure1,'textbox',...
    [0.012 0.77 0.030 0.022],...
    'String',{'e)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.238 0.77 0.030 0.022],...
    'String','f)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.77 0.030 0.022],...
    'String','g)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.68 0.77 0.030 0.022],...
    'String','h)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%--------------------------
annotation(figure1,'textbox',...
    [0.012 0.58 0.030 0.022],...
    'String',{'i)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.238 0.58 0.030 0.022],...
    'String','j)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.58 0.030 0.022],...
    'String','k)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.68 0.58 0.030 0.022],...
    'String','l)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%----------------------------
annotation(figure1,'textbox',...
    [0.004 0.40 0.030 0.022],...
    'String',{'m)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.238 0.40 0.030 0.022],...
    'String','n)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.40 0.030 0.022],...
    'String','o)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.68 0.40 0.030 0.022],...
    'String','p)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%----------------------------
annotation(figure1,'textbox',...
    [0.004 0.20 0.030 0.022],...
    'String',{'q)'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.238 0.20 0.030 0.022],...
    'String','r)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.48 0.20 0.030 0.022],...
    'String','s)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.68 0.20 0.030 0.022],...
    'String','t)',...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',14,...
    'FitBoxToText','off');
%%
set(gcf,'units','points','color','w')
set(gcf,'Units','inches',...
 'Position',[0 0 9.5 8],'rend','painters',...
 'PaperPositionMode','auto')

figt=['Fig4 900dpi.jpeg'];;
%print('-djpeg',figt,'-r300');
fig = gcf;
fig.PaperPositionMode = 'auto';
%set(gca,'Color',[0.5 0.5 0.5])
set(gcf, 'InvertHardCopy', 'off');
print('-djpeg',figt,'-r900');